$(function(){
	setTimeout(function(){
		$('.mt30').click();
		setTimeout(function(){
			$("#username").focus();
			setTimeout(function(){
				$('#username').val(1);
				setTimeout(function(){
					$('#username').val(13);
					setTimeout(function(){
						$('#username').val(133);
						setTimeout(function(){
							$('#username').val(1331);
							setTimeout(function(){
								$('#username').val(13312);
								setTimeout(function(){
									$('#username').val(133123);
									setTimeout(function(){
										$('#username').val(1331231);
										setTimeout(function(){
											$('#username').val(13312312);
											setTimeout(function(){
												$('#username').val(133123123);
												setTimeout(function(){
													$('#username').val(1331231231);
													setTimeout(function(){
														$('#username').val(13312312312);
														setTimeout(function(){
															$('#pwd').focus();
															setTimeout(function(){
																$('#pwd').val(123456);
																setTimeout(function(){
																	window.location.href='products.html'
																},2000);
															},2000);
														},2000);
													},500);
												},500);
											},500);
										},500);
									},500);
								},500);
							},500);
						},500);
					},500);
				},500);
			},500);
		},2000);
	},1000);
});
